//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JichangeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class apiurl_details
    {
        public long sno { get; set; }
        public string regip_test { get; set; }
        public string invip_test { get; set; }
        public string tokenip_test { get; set; }
        public string verifyip_test { get; set; }
        public string regip_live { get; set; }
        public string invip_live { get; set; }
        public string tokenip_live { get; set; }
        public string verifyip_live { get; set; }
        public string testcn { get; set; }
        public string livecn { get; set; }
        public string cert_serial { get; set; }
        public string cert_key { get; set; }
        public string res1 { get; set; }
        public string res2 { get; set; }
        public string res3 { get; set; }
        public string res4 { get; set; }
        public string res5 { get; set; }
        public string res6 { get; set; }
        public string res7 { get; set; }
        public string res8 { get; set; }
        public string res9 { get; set; }
        public string res10 { get; set; }
    }
}
