//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JichangeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class audit_log
    {
        public long audit_sno { get; set; }
        public string audit_type { get; set; }
        public string table_name { get; set; }
        public string column_name { get; set; }
        public string old_value { get; set; }
        public string new_value { get; set; }
        public string posted_by { get; set; }
        public Nullable<System.DateTime> posted_date { get; set; }
        public Nullable<System.DateTime> posted_time { get; set; }
        public Nullable<long> comp_mas_sno { get; set; }
    }
}
