//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JichangeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class batch_wise_item_issues
    {
        public long batch_item_iss_sno { get; set; }
        public Nullable<System.DateTime> iss_date { get; set; }
        public Nullable<long> warehouse_id { get; set; }
        public Nullable<long> grn_id { get; set; }
        public string batch_no { get; set; }
        public Nullable<long> item_code { get; set; }
        public Nullable<decimal> issue_qty { get; set; }
        public Nullable<decimal> item_price { get; set; }
        public Nullable<long> supplier_id { get; set; }
        public string batch_status { get; set; }
        public Nullable<long> refference_no { get; set; }
    }
}
