//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JichangeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public company_master()
        {
            this.company_bank_details = new HashSet<company_bank_details>();
            this.company_deposit_account = new HashSet<company_deposit_account>();
            this.invoice_ammendment = new HashSet<invoice_ammendment>();
            this.invoice_cancellation = new HashSet<invoice_cancellation>();
            this.company_users = new HashSet<company_users>();
            this.customer_master = new HashSet<customer_master>();
            this.invoice_master = new HashSet<invoice_master>();
            this.registration_ack = new HashSet<registration_ack>();
            this.roles_master = new HashSet<roles_master>();
            this.token_ack = new HashSet<token_ack>();
            this.zreport_details = new HashSet<zreport_details>();
        }
    
        public long comp_mas_sno { get; set; }
        public string company_name { get; set; }
        public string pobox_no { get; set; }
        public string physical_address { get; set; }
        public Nullable<long> region_id { get; set; }
        public Nullable<long> district_sno { get; set; }
        public Nullable<long> ward_sno { get; set; }
        public string tin_no { get; set; }
        public string vat_no { get; set; }
        public string director_name { get; set; }
        public string email_address { get; set; }
        public string telephone_no { get; set; }
        public string fax_no { get; set; }
        public string mobile_no { get; set; }
        public byte[] comp_logo { get; set; }
        public byte[] director_digital_sig { get; set; }
        public string posted_by { get; set; }
        public Nullable<System.DateTime> posted_date { get; set; }
        public string status { get; set; }
        public Nullable<long> branch_sno { get; set; }
        public Nullable<long> sus_acc_sno { get; set; }
        public string checker { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<company_bank_details> company_bank_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<company_deposit_account> company_deposit_account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoice_ammendment> invoice_ammendment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoice_cancellation> invoice_cancellation { get; set; }
        public virtual suspense_account suspense_account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<company_users> company_users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_master> customer_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoice_master> invoice_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<registration_ack> registration_ack { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<roles_master> roles_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<token_ack> token_ack { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zreport_details> zreport_details { get; set; }
    }
}
