//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JichangeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_bank_details
    {
        public long comp_bank_det_sno { get; set; }
        public Nullable<long> comp_mas_sno { get; set; }
        public string bank_name { get; set; }
        public string bank_branch { get; set; }
        public string account_no { get; set; }
        public string swift_code { get; set; }
    
        public virtual company_master company_master { get; set; }
    }
}
