//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JichangeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_users
    {
        public long comp_users_sno { get; set; }
        public Nullable<long> comp_mas_sno { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string user_type { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public string f_login { get; set; }
        public Nullable<long> sno { get; set; }
        public string q_name { get; set; }
        public string q_ans { get; set; }
        public Nullable<int> log_att { get; set; }
        public Nullable<System.DateTime> log_time { get; set; }
        public string log_status { get; set; }
        public string user_fullname { get; set; }
        public string email_address { get; set; }
        public string mobile_no { get; set; }
        public string localization { get; set; }
        public string flag { get; set; }
        public Nullable<System.DateTime> ctime { get; set; }
        public Nullable<long> user_position { get; set; }
        public Nullable<int> mail_status { get; set; }
        public string posted_by { get; set; }
        public Nullable<System.DateTime> posted_date { get; set; }
    
        public virtual company_master company_master { get; set; }
        public virtual reg_question reg_question { get; set; }
    }
}
