//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JichangeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer_master()
        {
            this.invoice_ammendment = new HashSet<invoice_ammendment>();
            this.invoice_cancellation = new HashSet<invoice_cancellation>();
            this.invoice_master = new HashSet<invoice_master>();
        }
    
        public long cust_mas_sno { get; set; }
        public string customer_name { get; set; }
        public string pobox_no { get; set; }
        public string physical_address { get; set; }
        public Nullable<long> region_id { get; set; }
        public Nullable<long> district_sno { get; set; }
        public Nullable<long> ward_sno { get; set; }
        public string tin_no { get; set; }
        public string vat_no { get; set; }
        public string contact_person { get; set; }
        public string email_address { get; set; }
        public string mobile_no { get; set; }
        public string posted_by { get; set; }
        public Nullable<System.DateTime> posted_date { get; set; }
        public Nullable<long> comp_mas_sno { get; set; }
        public string checker { get; set; }
        public string n_status { get; set; }
    
        public virtual company_master company_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoice_ammendment> invoice_ammendment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoice_cancellation> invoice_cancellation { get; set; }
        public virtual district_master district_master { get; set; }
        public virtual region_master region_master { get; set; }
        public virtual ward_master ward_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoice_master> invoice_master { get; set; }
    }
}
