//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JichangeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class grn_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public grn_master()
        {
            this.grn_details = new HashSet<grn_details>();
        }
    
        public long grn_id { get; set; }
        public Nullable<System.DateTime> grn_date { get; set; }
        public Nullable<long> prn_id { get; set; }
        public string received_by { get; set; }
        public string inspected_by { get; set; }
        public string remarks { get; set; }
        public Nullable<long> warehouse_id { get; set; }
        public string payment_mode { get; set; }
        public Nullable<long> supp_mas_sno { get; set; }
        public string supplier_invoice_no { get; set; }
        public string currency_code { get; set; }
        public string posted_by { get; set; }
        public System.DateTime posted_date { get; set; }
    
        public virtual currency_master currency_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<grn_details> grn_details { get; set; }
        public virtual supplier_master supplier_master { get; set; }
    }
}
