//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JichangeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class internal_transfer_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public internal_transfer_master()
        {
            this.internal_transfer_details = new HashSet<internal_transfer_details>();
        }
    
        public long itn_id { get; set; }
        public Nullable<System.DateTime> itn_date { get; set; }
        public Nullable<long> itn_from { get; set; }
        public Nullable<long> itn_to { get; set; }
        public string remarks { get; set; }
        public string status { get; set; }
        public string posted_by { get; set; }
        public System.DateTime posted_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<internal_transfer_details> internal_transfer_details { get; set; }
    }
}
