//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JichangeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class internal_transfer_details
    {
        public long int_tr_det_id { get; set; }
        public Nullable<long> itn_id { get; set; }
        public Nullable<long> item_code { get; set; }
        public Nullable<decimal> quantity_requested { get; set; }
        public Nullable<decimal> quantity_available { get; set; }
    
        public virtual internal_transfer_master internal_transfer_master { get; set; }
    }
}
