//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JichangeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_adjustments
    {
        public long inv_adj_sno { get; set; }
        public Nullable<System.DateTime> transaction_date { get; set; }
        public Nullable<long> warehouse_id { get; set; }
        public Nullable<long> item_code { get; set; }
        public string transaction_type { get; set; }
        public Nullable<decimal> item_computer_stock { get; set; }
        public Nullable<decimal> transaction_qty { get; set; }
        public Nullable<long> adjustment_code { get; set; }
        public string remarks { get; set; }
        public Nullable<decimal> physical_qty { get; set; }
        public string ia_batch_no { get; set; }
        public Nullable<decimal> item_price { get; set; }
        public string posted_by { get; set; }
        public System.DateTime posted_date { get; set; }
    }
}
