//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JichangeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice_details
    {
        public long inv_det_sno { get; set; }
        public Nullable<long> inv_mas_sno { get; set; }
        public string item_description { get; set; }
        public Nullable<decimal> item_qty { get; set; }
        public Nullable<decimal> item_unit_price { get; set; }
        public Nullable<decimal> item_total_amount { get; set; }
        public Nullable<decimal> vat_percentage { get; set; }
        public Nullable<decimal> vat_amount { get; set; }
        public Nullable<decimal> item_without_vat { get; set; }
        public string remarks { get; set; }
        public string vat_category { get; set; }
        public string vat_type { get; set; }
    
        public virtual invoice_master invoice_master { get; set; }
    }
}
