//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JichangeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_opening_stock
    {
        public long item_op_st_sno { get; set; }
        public Nullable<long> item_code { get; set; }
        public string item_name { get; set; }
        public Nullable<long> item_group_code { get; set; }
        public Nullable<long> item_sub_group_code { get; set; }
        public Nullable<long> warehouse_id { get; set; }
        public Nullable<decimal> item_op_qty { get; set; }
        public string posted_by { get; set; }
        public System.DateTime posted_date { get; set; }
    }
}
