//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JichangeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_transactions
    {
        public long item_tran_sno { get; set; }
        public Nullable<long> item_code { get; set; }
        public Nullable<long> tr_no { get; set; }
        public string tr_batch_no { get; set; }
        public Nullable<decimal> tr_unit_price { get; set; }
        public Nullable<long> tr_supplier { get; set; }
        public string tr_pay_type { get; set; }
        public Nullable<System.DateTime> tr_date { get; set; }
        public string tr_type { get; set; }
        public string tr_details { get; set; }
        public Nullable<long> tr_qty { get; set; }
        public string tr_narration { get; set; }
        public Nullable<decimal> tr_debit_qty { get; set; }
        public Nullable<decimal> tr_credit_qty { get; set; }
        public Nullable<long> tr_location { get; set; }
    }
}
