//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JichangeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_return_stores_details
    {
        public long item_ret_st_det_id { get; set; }
        public Nullable<long> item_return_id { get; set; }
        public Nullable<long> item_code { get; set; }
        public Nullable<long> quantity { get; set; }
        public string rts_batch_no { get; set; }
    
        public virtual item_return_stores_master item_return_stores_master { get; set; }
    }
}
