//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JichangeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_units
    {
        public long item_unit_sno { get; set; }
        public Nullable<long> item_code { get; set; }
        public string level_description { get; set; }
        public Nullable<decimal> conversion_factor { get; set; }
    
        public virtual item_master item_master { get; set; }
    }
}
