//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JichangeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_return_stores_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public item_return_stores_master()
        {
            this.item_return_stores_details = new HashSet<item_return_stores_details>();
        }
    
        public long item_return_id { get; set; }
        public Nullable<System.DateTime> item_return_date { get; set; }
        public Nullable<long> grn_id { get; set; }
        public string remarks { get; set; }
        public string return_type { get; set; }
        public Nullable<long> warehouse_id { get; set; }
        public string posted_by { get; set; }
        public System.DateTime posted_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<item_return_stores_details> item_return_stores_details { get; set; }
    }
}
