//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JichangeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public item_master()
        {
            this.item_units1 = new HashSet<item_units>();
            this.purchase_requisition_details = new HashSet<purchase_requisition_details>();
        }
    
        public long item_code { get; set; }
        public string item_name { get; set; }
        public Nullable<long> item_group_code { get; set; }
        public Nullable<long> item_sub_group_code { get; set; }
        public string item_source_type { get; set; }
        public string item_source_country { get; set; }
        public string item_vat_applicable { get; set; }
        public Nullable<decimal> item_opening_stock { get; set; }
        public Nullable<decimal> item_re_order_level { get; set; }
        public Nullable<decimal> item_min_stock { get; set; }
        public Nullable<decimal> item_max_stock { get; set; }
        public string manufacturer_item_code { get; set; }
        public string item_size { get; set; }
        public string item_status { get; set; }
        public string item_units { get; set; }
        public Nullable<decimal> item_existing_stock { get; set; }
        public string posted_by { get; set; }
        public System.DateTime posted_date { get; set; }
    
        public virtual item_groups item_groups { get; set; }
        public virtual item_sub_groups item_sub_groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<item_units> item_units1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase_requisition_details> purchase_requisition_details { get; set; }
    }
}
