//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JichangeApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JICHANGEEntities1 : DbContext
    {
        public JICHANGEEntities1()
            : base("name=JICHANGEEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<apiurl_details> apiurl_details { get; set; }
        public virtual DbSet<audit_log> audit_log { get; set; }
        public virtual DbSet<batch_wise_item_issues> batch_wise_item_issues { get; set; }
        public virtual DbSet<branch_name> branch_name { get; set; }
        public virtual DbSet<company_bank_details> company_bank_details { get; set; }
        public virtual DbSet<company_deposit_account> company_deposit_account { get; set; }
        public virtual DbSet<company_master> company_master { get; set; }
        public virtual DbSet<company_users> company_users { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<currency_master> currency_master { get; set; }
        public virtual DbSet<customer_master> customer_master { get; set; }
        public virtual DbSet<designation_list> designation_list { get; set; }
        public virtual DbSet<district_master> district_master { get; set; }
        public virtual DbSet<email_text> email_text { get; set; }
        public virtual DbSet<emp_detail> emp_detail { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<grn_details> grn_details { get; set; }
        public virtual DbSet<grn_master> grn_master { get; set; }
        public virtual DbSet<internal_transfer_details> internal_transfer_details { get; set; }
        public virtual DbSet<internal_transfer_master> internal_transfer_master { get; set; }
        public virtual DbSet<inventory_adjustment_types> inventory_adjustment_types { get; set; }
        public virtual DbSet<inventory_adjustments> inventory_adjustments { get; set; }
        public virtual DbSet<invoice_ammendment> invoice_ammendment { get; set; }
        public virtual DbSet<invoice_cancellation> invoice_cancellation { get; set; }
        public virtual DbSet<invoice_details> invoice_details { get; set; }
        public virtual DbSet<invoice_master> invoice_master { get; set; }
        public virtual DbSet<item_groups> item_groups { get; set; }
        public virtual DbSet<item_master> item_master { get; set; }
        public virtual DbSet<item_opening_stock> item_opening_stock { get; set; }
        public virtual DbSet<item_return_stores_details> item_return_stores_details { get; set; }
        public virtual DbSet<item_return_stores_master> item_return_stores_master { get; set; }
        public virtual DbSet<item_sub_groups> item_sub_groups { get; set; }
        public virtual DbSet<item_transactions> item_transactions { get; set; }
        public virtual DbSet<item_units> item_units { get; set; }
        public virtual DbSet<localization_company> localization_company { get; set; }
        public virtual DbSet<localization_master> localization_master { get; set; }
        public virtual DbSet<payment_details> payment_details { get; set; }
        public virtual DbSet<purchase_requisition_details> purchase_requisition_details { get; set; }
        public virtual DbSet<purchase_requisition_master> purchase_requisition_master { get; set; }
        public virtual DbSet<reg_question> reg_question { get; set; }
        public virtual DbSet<region_master> region_master { get; set; }
        public virtual DbSet<registration_ack> registration_ack { get; set; }
        public virtual DbSet<registration_ack_details> registration_ack_details { get; set; }
        public virtual DbSet<roles_master> roles_master { get; set; }
        public virtual DbSet<service_error_logs> service_error_logs { get; set; }
        public virtual DbSet<sms_settings> sms_settings { get; set; }
        public virtual DbSet<sms_text> sms_text { get; set; }
        public virtual DbSet<smtp_settings> smtp_settings { get; set; }
        public virtual DbSet<standard_units> standard_units { get; set; }
        public virtual DbSet<supplier_master> supplier_master { get; set; }
        public virtual DbSet<suspense_account> suspense_account { get; set; }
        public virtual DbSet<table_details> table_details { get; set; }
        public virtual DbSet<temp_localization> temp_localization { get; set; }
        public virtual DbSet<token_ack> token_ack { get; set; }
        public virtual DbSet<track_details> track_details { get; set; }
        public virtual DbSet<user_otp> user_otp { get; set; }
        public virtual DbSet<vat_percentage> vat_percentage { get; set; }
        public virtual DbSet<ward_master> ward_master { get; set; }
        public virtual DbSet<warehouse_master> warehouse_master { get; set; }
        public virtual DbSet<warehouse_sub_locations> warehouse_sub_locations { get; set; }
        public virtual DbSet<zreport_details> zreport_details { get; set; }
    }
}
