//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JichangeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_requisition_details
    {
        public long prn_req_det_sno { get; set; }
        public Nullable<long> prn_id { get; set; }
        public Nullable<long> item_code { get; set; }
        public Nullable<decimal> quantity_requested { get; set; }
        public Nullable<decimal> quantity_approved { get; set; }
        public Nullable<decimal> quantity_available { get; set; }
        public string supplier_name_advised { get; set; }
        public Nullable<decimal> recommended_price { get; set; }
        public string remarks { get; set; }
    
        public virtual item_master item_master { get; set; }
        public virtual purchase_requisition_master purchase_requisition_master { get; set; }
    }
}
