//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JichangeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_requisition_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public purchase_requisition_master()
        {
            this.purchase_requisition_details = new HashSet<purchase_requisition_details>();
        }
    
        public long prn_id { get; set; }
        public Nullable<System.DateTime> prn_date { get; set; }
        public string prn_terms { get; set; }
        public Nullable<long> supp_mas_sno { get; set; }
        public string status { get; set; }
        public string details { get; set; }
        public string posted_by { get; set; }
        public System.DateTime posted_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase_requisition_details> purchase_requisition_details { get; set; }
        public virtual supplier_master supplier_master { get; set; }
    }
}
