//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JichangeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class registration_ack_details
    {
        public long reg_ack_det_sno { get; set; }
        public Nullable<long> reg_ack_sno { get; set; }
        public string tax_code { get; set; }
        public Nullable<int> tax_percentage { get; set; }
    
        public virtual registration_ack registration_ack { get; set; }
    }
}
