//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JichangeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class registration_ack
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public registration_ack()
        {
            this.registration_ack_details = new HashSet<registration_ack_details>();
        }
    
        public long reg_ack_sno { get; set; }
        public Nullable<int> ack_code { get; set; }
        public string ack_message { get; set; }
        public string regid { get; set; }
        public string serial { get; set; }
        public string uin { get; set; }
        public Nullable<int> tin_no { get; set; }
        public string vrn { get; set; }
        public string mobile_no { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string address { get; set; }
        public string country { get; set; }
        public string company_name { get; set; }
        public string receiptcode { get; set; }
        public string region { get; set; }
        public Nullable<long> gc { get; set; }
        public string taxoffice { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string tokenpath { get; set; }
        public string posted_by { get; set; }
        public Nullable<System.DateTime> posted_date { get; set; }
        public Nullable<long> comp_mas_sno { get; set; }
        public string pfx_password { get; set; }
        public string cert_serial { get; set; }
        public string certificate_path { get; set; }
        public string invoice_path { get; set; }
        public string log_path { get; set; }
    
        public virtual company_master company_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<registration_ack_details> registration_ack_details { get; set; }
    }
}
