//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JichangeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class roles_master
    {
        public long sno { get; set; }
        public string code { get; set; }
        public string descript { get; set; }
        public string admin1 { get; set; }
        public string role_status { get; set; }
        public Nullable<long> comp_mas_sno { get; set; }
        public string posted_by { get; set; }
        public Nullable<System.DateTime> posted_date { get; set; }
    
        public virtual company_master company_master { get; set; }
    }
}
