//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JichangeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_text
    {
        public long sno { get; set; }
        public string flow_id { get; set; }
        public string sms_text1 { get; set; }
        public Nullable<System.DateTime> effective_date { get; set; }
        public string sms_sub { get; set; }
        public string sms_sub_local { get; set; }
        public string sms_text_other { get; set; }
        public string posted_by { get; set; }
        public Nullable<System.DateTime> posted_date { get; set; }
    }
}
