//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JichangeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class standard_units
    {
        public long stan_unit_sno { get; set; }
        public string unit { get; set; }
        public string posted_by { get; set; }
        public System.DateTime posted_date { get; set; }
    }
}
