//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JichangeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public supplier_master()
        {
            this.grn_master = new HashSet<grn_master>();
            this.purchase_requisition_master = new HashSet<purchase_requisition_master>();
        }
    
        public long supp_mas_sno { get; set; }
        public string supp_name { get; set; }
        public string pobox_no { get; set; }
        public string physical_address { get; set; }
        public Nullable<long> region_id { get; set; }
        public Nullable<long> district_sno { get; set; }
        public Nullable<long> ward_sno { get; set; }
        public string tin_no { get; set; }
        public string vat_no { get; set; }
        public string contact_person { get; set; }
        public string email_address { get; set; }
        public string mobile_no { get; set; }
        public string posted_by { get; set; }
        public System.DateTime posted_date { get; set; }
    
        public virtual district_master district_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<grn_master> grn_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase_requisition_master> purchase_requisition_master { get; set; }
        public virtual region_master region_master { get; set; }
        public virtual ward_master ward_master { get; set; }
    }
}
