//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JichangeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_localization
    {
        public long loc_sno { get; set; }
        public string loc_eng { get; set; }
        public string dyn_eng { get; set; }
        public string table_name { get; set; }
        public string column_name { get; set; }
        public string dyn_swa { get; set; }
    }
}
