//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JichangeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class token_ack
    {
        public long token_ack_sno { get; set; }
        public string access_token { get; set; }
        public string token_type { get; set; }
        public string expire_in { get; set; }
        public string routing_key { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<long> comp_mas_sno { get; set; }
    
        public virtual company_master company_master { get; set; }
    }
}
