//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JichangeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class track_details
    {
        public long sno { get; set; }
        public string full_name { get; set; }
        public string ipadd { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> login_time { get; set; }
        public string posted_by { get; set; }
        public string descrip { get; set; }
        public Nullable<System.DateTime> logout_time { get; set; }
        public Nullable<long> comp_mas_sno { get; set; }
    }
}
