//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JichangeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class zreport_details
    {
        public long zreport_sno { get; set; }
        public Nullable<System.DateTime> zreport_date { get; set; }
        public string zreport_status { get; set; }
        public string posted_by { get; set; }
        public Nullable<System.DateTime> posted_date { get; set; }
        public Nullable<long> comp_mas_sno { get; set; }
    
        public virtual company_master company_master { get; set; }
    }
}
